services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_MODELS=llama3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      ollama:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - ./app:/app

volumes:
  ollama_data: 